# Site settings
title: Trepanger
email: zbwrnz@gmail.com
description: >
    Blog and website of Zebulun Arendsee
baseurl: ""
url: "https://arendsee.github.io"
github_username: arendsee
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
