# Site settings
title: Home
email: zbwrnz@gmail.com
description: >

disqus_shortname: http-arendsee-github-io
baseurl: ""
url: "https://arendsee.github.io"
github_username: arendsee
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
